---
stages:
  - name: "lint"
  - name: "test"
  - name: "deploy-pypi"
    if: "tag IS present"

language: "python"
python:
  - "3.6"
  - "3.7"
  - "3.8"

services:
  - "docker"

# --------------------------------------------------------------------------
# Tests
# --------------------------------------------------------------------------
before_script:
  - "pip install invoke toml docker-compose poetry"

script:
  - "invoke build --nocache --python-ver $TRAVIS_PYTHON_VERSION"
  - "invoke unittest --python-ver $TRAVIS_PYTHON_VERSION"

jobs:
  include:
    - stage: "lint"
      before_script:
        - "pip install invoke toml docker-compose"
        - "invoke build --nocache --python-ver $TRAVIS_PYTHON_VERSION"
      script:
        - "invoke black --python-ver $TRAVIS_PYTHON_VERSION"
        - "invoke flake8 --python-ver $TRAVIS_PYTHON_VERSION"
        - "invoke bandit --python-ver $TRAVIS_PYTHON_VERSION"
        # - "invoke pydocstyle --python-ver $TRAVIS_PYTHON_VERSION"
        - "invoke pylint --python-ver $TRAVIS_PYTHON_VERSION"
